version: '3.8'
services:
  logreaderbackend:
    build: .
    container_name: 'Logreader-Backend'
    ports:
      - "4001:4001"
    networks: 
      - logreader-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  nginx:
    image: nginx:latest
    container_name: 'nginx-proxy'
    ports:
      - "80:80"  
    volumes:
      - ./nginx:/etc/nginx/conf.d  
      - ./frontend/build:/usr/share/nginx/html  
    depends_on:
      - logreaderbackend
    networks:
      - logreader-network
networks:
  logreader-network:
    name: logreader-network
