version: '3.8'
services:
  logreaderbackend:
    build: .
    container_name: 'Logreader-Backend'
    networks:
      - logreader-network
    ports:
      - "4001:4001"
  nginx:
    image: nginx:alpine
    container_name: 'nginx-reverse-proxy'
    ports:
      - "3001:3001"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - logreaderbackend
    networks:
      - logreader-network

networks:
  logreader-network:
    name: logreader-network
